### ISSUE TITLE
june 2nd recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#58]
follows #57 

## brief:
PYDATALOG SUCKSZZZZ LOL XD
we pushed `feature-client-only` to master, and went over the engine (in an abstract fashion). 
we intend to refactor the engine abstract class, the micro-passes, and add an sql engine.

## TODOs:

- [x] understand the engine better:
   * by using `debug=True`, 
   * by setting a breakpoint in the for-loop of the pass execution
   * by reading the document description
- [x] understand the ~7 relational algebra operators, and basic sql operators
- [x] add the relational algebra operators to `MySQLEngine`, inside the new `feature-engine` branch
- [x] go over the term-graph nodes and add metadata if needed
- [x] modify, add, and delete the current passes as needed
- [x] use pseudo-code if we're not sure how to begin implementation

the next meeting is scheduled for june 16th, 8 pm
