### ISSUE TITLE
june 16th recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#62]
follows #58 

## brief:
we've talked about our next steps regarding the new engine, and showed a few examples (seen here: #61)

## TODOs:

- [x] finish the examples in #61:
  * the first one - done
  * for the recursive example - use the utility article
- [x] learn `networkx` basics
- [x] understand how to use `networkx` for passes (it is used in the last pass)
- [x] write pseudo code for the sql engine - it should describe how to convert queries into trees
- [x] invite dean on outlook

the next meeting is scheduled for july 27th, 19:30
