### ISSUE TITLE
july 27th recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#63]
follows #62

## brief:
we've talked about transforming rules into netx trees, using bounding graphs and ignoring (almost) all optimizations.
we went over a few edge cases, and typed some pseudo code.

## TODOs:

- [x] @DeanLight needs to do some math and prove that recursive rules are DAGs (except for self-cycles)
- [x] implement the pseudo code which was typed during the meeting
- [x] implement the complete term graph as a fusion of every term's computation graph
- [x] implement the basic SQL operators
- [x] test non-recursive rules

the next meeting is scheduled for august 11th, 19:00
