### ISSUE TITLE
august 11th recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#64]
follows #63 

## brief:
we went over everything we have left to finish the project, including recursive rules and code reviews.

## TODOs:
- [x] implement (mutually) recursive rules using the naive method (mentioned in #63). pseudo code:
![image](https://user-images.githubusercontent.com/45516943/129073317-4735f0d5-3b21-4642-89d0-0d9091dccb74.png)
- [x] make sure all previous tests pass
- [x] submit code review

the next meeting is scheduled for september 1st, 19:00
