### ISSUE TITLE
august 30th recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#66]
follows #64  

## brief:
we went over terminology issues, and are about to start the code review

## TODOs:
- [x] rename term/dependency graph
- [x] refactor relation_to_id
- [x] code review
- [x] refactor the README - split it into a basic README like in most git repos, and a scientific thing (into which we will move the long explanations and diagrams of the current README)

the next meeting is scheduled for september 13th, 19:00
