### ISSUE TITLE
september 13th recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#67]
follows #66

## brief:
we went over the relation between the graphs, the execution function, jinja, 

## TODOs:
- [x] jinja - first organize data, then send to jinja (or format string where jinja isn't needed)
- [x] refactor execution (split into two files, execution is a file)
- [x] finish file docstring in graphs
- [x] refactor dfs functions
- [x] session move all init objects into params
- [x] add global logger variables to every module which uses logging

the next meeting is scheduled for september 27th, 19:00
