### ISSUE TITLE
september 30th recap

### ISSUE THREAD

**Issue by nnrepos** [DeanLight/spannerlib#69]
follows #67

## brief:
we merged the engine branch without completing a few final bugs, and we are ready to present our project

## TODOs:
- [x] create 3 new branches:
  - [x] a branch from the unfinished bugs
  - [x] a branch for the optimization in the notebook
  - [x] a temporary branch which contains the presentation (maybe jupyter?)

the next meeting was not scheduled yet
